DROP TABLE IF EXISTS Albums;
DROP TABLE IF EXISTS Photos;

CREATE TABLE Albums (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  coverImage TEXT NOT NULL,
  photoCount INTEGER DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Photos (
  id TEXT PRIMARY KEY,
  albumId TEXT NOT NULL,
  url TEXT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (albumId) REFERENCES Albums(id) ON DELETE CASCADE
);